care_coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')), 

    path('account/', include('useraccount.urls', namespace="account")), 
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('shop/', include('shop.urls', namespace='shop') ),
    

    path('', lambda request: redirect('shop/', permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
   
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),

    path('pay/<int:order_id>/', views.order_pay, name='order_pay'),
    path('success/<int:order_id>/', views.order_success, name='order_success'),

    path('failed/<int:order_id>/', views.payment_failed, name='payment_failed'),

    path('chapa/webhook/', views.chapa_callback, name='chapa_callback'),

]

shop/urls.py
from django.urls import path
from . import views

app_name="shop"

urlpatterns =[
    path('', views.product_list, name="product-list"),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )

    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart

from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form  = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override']),
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True}
        )

    return render(request,
                  'cart/cart_detail.html',
                  {'cart':cart})

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}?v=3">
{% endblock %}

{% block content %}
<h1>Your Cart</h1>

{% if cart|length > 0 %}
<table class="cart-table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td>
                <form method="post" action="{% url 'cart:cart_add' item.product.id %}">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <button type="submit" class="btn-update">Update</button>
                </form>
            </td>
            <td>${{ item.price }}</td>
            <td>${{ item.total_price }}</td>
            <td>
                <form method="post" action="{% url 'cart:cart_remove' item.product.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn-remove">Remove</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right"><strong>Total:</strong></td>
            <td colspan="2"><strong>${{ cart.get_total_price }}</strong></td>
        </tr>
    </tfoot>
</table>

<div class="cart-buttons">
    <a href="{% url 'shop:product-list' %}" class="btn-add-items">Add Items</a>
    {% if cart|length > 0 %}
        <a href="{% url 'order:order_create' %}" class="btn-order">Place Order</a>
    {% else %}
        <button class="btn-order" disabled>Place Order</button>
    {% endif %}
</div>

{% else %}
<p>Your cart is empty.</p>
<a href="{% url 'shop:product-list' %}">Go back to shop</a>
{% endif %}
{% endblock %}