care_coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')), 

    path('account/', include('useraccount.urls', namespace="account")), 
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('shop/', include('shop.urls', namespace='shop') ),
    

    path('', lambda request: redirect('shop/', permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
   
]

shop/urls.py
from django.urls import path
from . import views

app_name="shop"

urlpatterns =[
    path('', views.product_list, name="product-list"),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name= models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = "category"
        verbose_name_plural="categories"
        
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='products'
    )

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]


    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
# Create your views here.

def product_list(request):
    
    categories = Category.objects.all()
    selected_categories = request.GET.getlist('category')
    
    products = Product.objects.filter(available=True)
    if selected_categories:
        products = products.filter(category__slug__in=selected_categories)
    
    
    return render(request,
                  'shop/product/product_list.html',
                  {'categories': categories,
                   'products':products,
                   'selected_categories':selected_categories,
                   })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True) 
    
    return render(request,
                  'shop/product/product_detail.html',
                  {'product': product})
    

shop/templates/shop/product/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'shop/css/detail.css' %}?v=2">
{% endblock %}
{% block content %}

<div class="form-card">
  <div class="product-image">
    {% if product.image %}
      <img src="{{ product.image.url }}" alt="{{ product.name }}">
    {% else %}
      <img src="{% static 'img/placeholder.png' %}" alt="No Image">
    {% endif %}
  </div>

  <div class="product-info">
    <h1>{{ product.name }}</h1>
    <p class="price">${{ product.price }}</p>
    <p class="description">{{ product.description }}</p>

    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add-to-cart-form">
      {% csrf_token %}
      <div class="quantity-field">
        <label for="quantity">Quantity:</label>
        <input 
          type="number" 
          id="quantity" 
          name="quantity" 
          value="1" 
          min="1" 
          max="10"
          class="quantity-input"
        >
      </div>
      <button type="submit" class="add-to-cart-btn">Add to Cart</button>
    </form>
  </div>
</div>
{% endblock %}

shop/templates/shop/product/product_list.html
{% extends "base.html" %}
{% load static %}


{% block extra_css %}
    <link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <div class="sidebar">
        <form method="get">

            <h4>Filter by Category</h4>
            {% for category in categories %}
                <label>
                    <input type="checkbox" name="category" value="{{ category.slug }}"
                        {% if category.slug in selected_categories %}checked{% endif %}>
                    {{ category.name }}
                </label>
            {% endfor %}
            <button type="submit" class="apply-btn">Apply</button>
        </form>
    </div>

    <div class="product-grid">
        {% for product in products %}
        <div class="product-card">
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
            {% else %}
                <img src="{% static 'img/placeholder.png' %}" alt="No Image">
            {% endif %}
            <div class="product-name">{{ product.name }}</div>
            <div class="product-price">${{ product.price }}</div>
              <a href="{% url 'shop:product_detail' product.id product.slug %}" class="detail-arrow"> →</a>  
        </div>
        {% empty %}
        <p>No products available.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}