care_coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')), 

    path('account/', include('useraccount.urls', namespace="account")), 
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('shop/', include('shop.urls', namespace='shop') ),
    

    path('', lambda request: redirect('shop/', permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
   
]

shop/urls.py
from django.urls import path
from . import views

app_name="shop"

urlpatterns =[
    path('', views.product_list, name="product-list"),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

useraccount/urls.py
from django.urls import path
from . import views

app_name="account"

urlpatterns = [
    path('register/', views.register_view, name="register"), 
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

    path('edit_profile/', views.edit_profile, name="edit_profile"),
    



    path('request-password-reset/', views.request_password_reset, name='request-password-reset'),
    path('reset-password/<int:user_id>/', views.reset_password, name='reset-password'),
    path('update-password/', views.update_password, name="update-password"),


    path('profile/show/', views.show_profile, name='show_profile'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">


    {% block extra_css %}{% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet" />
    <title>{% block title %}My Shop{% endblock %}</title>
</head>
<body>
  <header>
    <nav class="navbar">

      <div class="nav-left">
        <a href="{% url 'shop:product-list' %}" class="logo-link">
          <img src="/media/logos/logo.jpg"  alt="Site Logo" class="logo-img" />
          <span class="logo-text">Care Coffee</span>
        </a>
      </div>
            <div class="nav-right">
              {% if user.is_authenticated %}
                <div class="account-dropdown">
                    {% if user.profile.photo %}
                      <img src="{{ user.profile.photo.url }}" alt="Profile Photo" class="account-icon" />
                    {% else %}
                      <img src="/media/users/default/default.jpg" alt="Default Photo" class="account-icon" />
                    {% endif %}

                  <div class="dropdown-menu">
                    <a href="{% url 'account:show_profile' %}">My Profile</a>
                    <a href="{% url 'account:edit_profile' %}">Edit profile</a>
                    <a href="{% url 'account:logout' %}">Logout</a>
                  </div>
                </div>
              {% else %}
                <a href="{% url 'account:login' %}" class="btn-auth">Login</a>
              {% endif %}

      </div>
    </nav>
  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>